### PR TITLE
Add Sendable conformances

### PR DESCRIPTION
**Pull request by ffried**
**These changes are now available in [4.1.0](https://github.com/vapor/apns/releases/tag/4.1.0)**

This adds `Sendable` conformances to all types in this library.

### CODE REVIEW

**Comment by ffried** [comment]
This currently depends on https://github.com/swift-server-community/APNSwift/pull/195 to be free of warnings, but in general all types should be safe to use across threads.

**Review by 0xTim — CHANGES_REQUESTED** [review]
Thanks for this! In order to stop us shooting ourselves in the foot we can change this to use `NIOLockedValueBox` instead which makes things that need to be mutable constant, removing the need for `@unchecked`. Since everything is locked anyway there's no performance hit

**Comment by ffried** [comment]
@0xTim Good point. I had to make the class `final` however (otherwise, `@unchecked` would still be necessary). It shouldn't break anything, though, since it was never `open` - so no subclasses can exist outside of the module.

Also, I removed the unused lock from `Application.APNS`.

**Review by 0xTim — APPROVED** [review]
Thanks!

**Review by 0xTim — CHANGES_REQUESTED** [review]
@ffried actually I do have one request - can you add a 5.9 manifest with complete concurrency checking turned on, that will show up any sendable issues on CI and when people run the package locally. See the Vapor repo for an example

**Comment by ffried** [comment]
@0xTim Done

**Review by 0xTim — APPROVED** [review]
Thanks!

**Comment by 0xTim** [comment]
@ffried Finally can you update the test workflow - I think the reusable workflow branch has been merged so you can point to main now (like Vapor again)

**Comment by ffried** [comment]
@0xTim Also done

**Comment by 0xTim** [comment]
Thanks, we're good to go!

**Pull request merged**
