### PR TITLE
Update to new major version of APNSwift

### PR DESCRIPTION
**Pull request by code28**
Updates the dependency to the new major version of APNSwift and new location for the package.

This is a major release because of API changes but should be backwards compatible for the most part.

### CODE REVIEW

**Comment by 0xTim** [comment]
Given APNSwift contains a breaking change that most people will hit I don't think we should do this. Most people aren't going to choose which version they take and they only depend on this library so this will likely be a breaking change. If we're going to add a breaking change we might as well remove support for v3 altogether

**Comment by kylebrowning** [comment]
Agreed. I just merged a major change into Apnswift so it's time

**Comment by code28** [comment]
Thanks for your fast reaction! No problem, I'm totally fine with releasing a new major version and removing support for v3 of APNSwift!
The change is applied.

**Review by kylebrowning — APPROVED** [review]

**Comment by 0xTim** [comment]
@kylebrowning what's changed in the new major version of APNSwift? Basically do we need to update https://docs.vapor.codes/advanced/apns/

**Comment by code28** [comment]
> @kylebrowning what's changed in the new major version of APNSwift? Basically do we need to update https://docs.vapor.codes/advanced/apns/

I'm not kylebrowning, but I think I can answer as well, since my PR made the new major version necessary:
Only the handling of (custom) loggers changed. Since logging of APNS is not covered in the Vapor docs, maybe only the version number should be updated, but otherwise it's fine.

**Comment by 0xTim** [comment]
Original comment:
With this change, the new major version of APNSwift is enabled, so that the user can decide on their own, if they want to use version 3 or 4 of APNSwift.

Both should work without any changes in this repo, so I decided to use the range in the Package.swift. If you prefer to release a new major version here as well, it'd be fine for me, too.

**Comment by 0xTim** [comment]
Cool, so this is good to go other than CI not triggering. I'll take a look at it later unless you want to have a go

**Pull request merged**
